#ifndef _UVC_GADGET_H_
#define _UVC_GADGET_H_

#include <linux/ioctl.h>
#include <linux/types.h>
#include <linux/usb/ch9.h>

#define UVC_EVENT_FIRST (UVC_EVENT_PRIVATE_START + 0)
#define UVC_EVENT_CONNECT (UVC_EVENT_PRIVATE_START + 0)
#define UVC_EVENT_DISCONNECT (UVC_EVENT_PRIVATE_START + 1)
#define UVC_EVENT_STREAMON (UVC_EVENT_PRIVATE_START + 2)
#define UVC_EVENT_STREAMOFF (UVC_EVENT_PRIVATE_START + 3)
#define UVC_EVENT_SETUP (UVC_EVENT_PRIVATE_START + 4)
#define UVC_EVENT_DATA (UVC_EVENT_PRIVATE_START + 5)
#define UVC_EVENT_LAST (UVC_EVENT_PRIVATE_START + 5)

#endif // !_UVC_GADGET_H_
